import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { SidebarProvider, SidebarTrigger } from '@/app/components/atoms/sidebar'
import { AppSidebar } from '@/app/components/organisms/sidebar/app-sidebar'
import { Toaster } from '@/app/components/atoms'
import '@/app/globals.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <main className="px-2 flex-1">
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  )
}
