FROM golang:1.21-alpine AS builder

WORKDIR /app

# install system dependencies
RUN apk add --no-cache git

COPY go.mod go.sum ./

RUN go mod download

COPY . .

# compile
RUN CGO_ENABLED=0 GOOS=linux go build -o pos-app main.go

# final stage
FROM alpine:3.18

WORKDIR /app

# create data directory
RUN mkdir -p /app/data

# copy compiled application
COPY --from=builder /app/pos-app .

# copy migration files
COPY --from=builder /app/internal/storage/sql/migration/scripts ./internal/storage/sql/migration/scripts

# set environment variables
ENV APP_MODE=production \
    DATABASE_DRIVER=sqlite \
    DATABASE_STORAGE_FILE_PATH=/app/data/pos.db

# run application
