version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "8002:8002"
    environment:
      - APP_MODE=development
      - DATABASE_DRIVER=postgres
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=pos_dev
      - DATABASE_SSL_MODE=disable
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pos_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: